# Generated by Django 3.2.8 on 2021-11-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50, null=True)),
                ('ethTokenAddress', models.CharField(max_length=100, null=True)),
                ('bscTokenAddress', models.CharField(max_length=100, null=True)),
                ('marketCap', models.IntegerField(default=0)),
            ],
        ),
    ]
