# Generated by Django 3.2.8 on 2021-11-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='marketCap',
            field=models.IntegerField(null=True),
        ),
    ]
