# Generated by Django 3.2.8 on 2021-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_alter_coin_marketcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
