# Generated by Django 3.2.8 on 2021-10-31 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoinCapData',
            fields=[
                ('website', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=100)),
                ('marketCap', models.IntegerField()),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinmarketcap.host')),
            ],
        ),
    ]
